[stable/redis-ha] Improve liveness probe for large databases (#14999)
* [stable/redis-ha] Improve liveness probe so that redis is not restarted while it is still loading its dataset into memory

On larger databases this can take more than just the initial probe delay. During this time redis will not answer the ping command with pong, but with loading. Of course the container should not be marked as ready, but it also should not restart which results in redis never starting successfully.

Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>

* [stable/redis-ha] Bump version to 3.5.2

Signed-off-by: Bastian Hofmann <bashofmann@gmail.com>
Signed-off-by: Sergey Nazarov <natarajaya@gmail.com>

diff --git a/stable/redis-ha/templates/redis-ha-healthchecks.yaml b/stable/redis-ha/templates/redis-ha-healthchecks.yaml
--- a/stable/redis-ha/templates/redis-ha-healthchecks.yaml
+++ b/stable/redis-ha/templates/redis-ha-healthchecks.yaml
@@ -39,3 +39,13 @@ data:
         echo "Server check failed with: $CHECK_SERVER"
         exit 1
     fi
+
+  liveness.sh: |
+    #!/bin/sh
+    set -eu
+    CHECK_SERVER="$(redis-cli -p "$1"{{ if .Values.auth }} -a "$AUTH"{{ end }} ping)"
+
+    if [ "$CHECK_SERVER" != "PONG" ] && [ "$CHECK_SERVER" != "LOADING Redis is loading the dataset in memory" ]; then
+        echo "Server check failed with: $CHECK_SERVER"
+        exit 1
+    fi
