[stable/airflow] add option to run airflow upgradedb in init-container
Signed-off-by: Benny Gächter <benny.gaechter@gmail.com>

diff --git a/stable/airflow/templates/config/configmap-scripts.yaml b/stable/airflow/templates/config/configmap-scripts.yaml
--- a/stable/airflow/templates/config/configmap-scripts.yaml
+++ b/stable/airflow/templates/config/configmap-scripts.yaml
@@ -58,3 +58,23 @@ data:
 
     echo "*** Initdb failed after ${COUNT} retries; failed."
     exit 1
+  upgrade-db.sh: |
+    #!/bin/bash
+    echo "*** Waiting 10s for database"
+    sleep 10
+
+    COUNT=0
+    while [ "${COUNT}" -lt 5 ]; do
+      echo "*** upgrading airflow db"
+      if airflow upgradedb || airflow db upgrade; then
+        echo "*** upgradedb succeeded"
+        exit 0
+      else
+        ((COUNT++))
+        echo "*** upgradedb failed: waiting 5s before retry #${COUNT}"
+        sleep 5
+      fi
+    done
+
+    echo "*** upgradedb failed after ${COUNT} retries; failed."
+    exit 1
